services:
  app:
    build: .
    container_name: event_management_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event_management_db
      SPRING_DATASOURCE_USERNAME: new_user
      SPRING_DATASOURCE_PASSWORD: new_password
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: event_management_db
    environment:
      POSTGRES_DB: event_management_db
      POSTGRES_USER: new_user
      POSTGRES_PASSWORD: new_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
